### ISSUE TITLE
node firestore2json.js users.json fails

### ISSUE THREAD

**Issue by Sun3** [supabase-community/firebase-to-supabase#8]
When you run the command `node firestore2json.js users.json` you received a message `0 records written to users.json.json`

But when you run `node collections.js` it does list the collections.

Any ideas?
Thank you.

**Comment by Sun3** [comment]
I am still trying to make it work, but no go. 

```
> node firestore/firestore2json.js location
OR ...
> node firestore/firestore2json.js location 1000 0

databaseURL https://myprojectname.firebaseio.com
0 records written to location.json
```

It creates the location.json file with the following content:
```

]
```


When I run to look at the collections it works fine:

```
> node firestore/collections.js 

databaseURL https://myprojectname.firebaseio.com
users
location
```


Any ideas?

**Comment by solkpolk** [comment]
Poor documentation. Try removing the `.json` 

works : `node firestore2json.js users`

**Comment by burggraf** [comment]
I have added the following to the documentation in order to make it more clear:

```
**note**: `<collectionName>` is just the name of the collection (do not add .json at the end of this on the command line
```
